trigger:
- master

pool: Default

stages:
- stage: Build
  jobs:
  - job: BuildJob
    dependsOn: LoginToIBMCloud
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '20.10.5'
    - bash: docker --version
    
- stage: Deploy
#   variables:
#     environment: Dev
  dependsOn: Build
  jobs:
    - job: DevDeployJob
      steps:
      - bash: echo DeployJob
      - task: oc-setup@2
        inputs:
          connectionType: 'OpenShift Connection Service'
          openshiftService: 'roks-cluster'