trigger:
- master

pool: Default

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - task: oc-setup@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'roks-cluster'
- stage: Deploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo $(environment)DeployJob