trigger:
- master

pool: Default

stages:
- stage: Build
  jobs:
  - job: InstallCLI
    steps:
    - bash: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
  - job: LoginToIBMCloud
    dependsOn: InstallCLI
    steps:
    - bash: ibmcloud login --apikey $(apikey)
  - job: BuildJob
    dependsOn: LoginToIBMCloud
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '20.10.5'
    - bash: docker --version
 #   - bash: sudo docker login -u iamapikey -p $(apikey) us.icr.io
    - bash: ibmcloud cr login
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: 'us.icr.io/azure-demo/java-test:v1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    
- stage: Deploy
#   variables:
#     environment: Dev
  dependsOn: Build
  jobs:
    - job: DevDeployJob
      steps:
      - bash: echo DeployJob
      - task: oc-setup@2
        inputs:
          connectionType: 'OpenShift Connection Service'
          openshiftService: 'roks-cluster'