trigger:
- master

pool: Default

stages:
- stage: Build
  jobs:
  - job: InstallCLIIbmCloud
    steps:
    - bash: curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash
  - job: LoginToIBMCloud
    steps:
    - bash: ibmcloud login --apikey $(apikey)
  - job: BuildJob
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - bash: docker --version
 #   - bash: sudo docker login -u iamapikey -p $(apikey) us.icr.io
    - bash: ibmcloud cr login
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: 'us.icr.io/azure-demo/java-test:v1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    
- stage: Deploy
#   variables:
#     environment: Dev
  dependsOn: Build
  jobs:
    - job: DevDeployJob
      steps:
      - bash: echo DeployJob
      - task: oc-setup@2
        inputs:
          connectionType: 'OpenShift Connection Service'
          openshiftService: 'roks-cluster'