apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: postgreSQL
    spec:
      containers:
        - image: ragudiko/postgres-9.6-spring-boot-demo
          name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: sampledb
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          emptyDir: {}
