# Dockerfile
FROM postgres:9.6

#RUN mkdir -p /tmp/psql_data/

#COPY *.sql /tmp/psql_data/

#RUN /etc/init.d/postgresql start && /usr/bin/psql
#COPY script.sh /docker-entrypoint-initdb.d/

RUN /etc/init.d/postgresql start

#RUN psql -U postgres -h localhost -d postgres -p 5434 -f create_db_user.sql
