apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
   app: postgres
spec:
  containers:
  - name: postgres
    image: ragudiko/postgres-9.6-spring-boot-demo
    ports:
      - containerPort: 5432
